# CloudCannon Configuration for Eleventy Site
paths:
  static: ''
  uploads: assets/images/uploads

timezone: Australia/Perth

markdown:
  engine: commonmark
  options:
    html: true
collections_config:
  pages:
    path: ''
    icon: wysiwyg
  docs:
    path: docs
    icon: docs
  src:
    path: src
    icon: abc
  src_writings:
    path: src/writings
    icon: hr_resting
