backend:
  name: github
  repo: hlnb/helenbee-site
  branch: main
  base_url: "https://www.helenburgess.id.au" # match deployed domain
  auth_endpoint: "/api/auth" # leading slash for absolute path

site_url: "https://www.helenburgess.id.au"

media_folder: "assets/images/uploads"
public_folder: "/assets/images/uploads"

publish_mode: editorial_workflow

collections:
  - name: "writings"
    label: "Writings"
    label_singular: "Writing"
    create: true
    folder: "src/writings"
    extension: "md"
    format: "frontmatter"
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    path: "{{year}}/{{month}}/{{slug}}"

    fields:
      - label: "Title"
        name: "title"
        widget: "string"

      - label: "Publish Date"
        name: "date"
        widget: "datetime"

      - label: "Excerpt"
        name: "excerpt"
        widget: "text"
        required: false

      - label: "Tags"
        name: "tags"
        widget: "list"
        default: ["writings"]

      - label: "Body"
        name: "body"
        widget: "markdown"
